# Generated by Django 4.0.2 on 2022-02-21 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add1', models.CharField(max_length=500)),
                ('add2', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
    ]
