# Generated by Django 4.0.2 on 2022-03-20 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_content_filter_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='data_filter',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
