# Generated by Django 4.0.2 on 2022-04-01 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_content_data_filter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Filter_Image/blog')),
                ('additional_image', models.ImageField(upload_to='Filter_Image/blog')),
                ('additional_image1', models.ImageField(upload_to='Filter_Image/blog')),
                ('title', models.CharField(max_length=300)),
                ('description1', models.CharField(max_length=300)),
                ('description2', models.CharField(max_length=300)),
                ('description3', models.CharField(max_length=300)),
                ('description4', models.CharField(max_length=300)),
                ('description5', models.CharField(max_length=300)),
                ('description6', models.CharField(max_length=300)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.categories')),
            ],
        ),
    ]
