# Generated by Django 4.0.2 on 2022-04-01 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_categories_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='additional_image',
            field=models.ImageField(blank=True, null=True, upload_to='Filter_Image/blog'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='additional_image1',
            field=models.ImageField(blank=True, null=True, upload_to='Filter_Image/blog'),
        ),
    ]
