# Generated by Django 4.0.2 on 2022-04-01 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_blog_additional_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='description1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='description2',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='description3',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='description4',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='description5',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='description6',
            field=models.TextField(),
        ),
    ]
