# Generated by Django 4.0.2 on 2022-04-01 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_blog_description1_alter_blog_description2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='status',
            field=models.CharField(blank=True, choices=[('Publish', 'Publish'), ('Draft', 'Draft')], max_length=200, null=True),
        ),
    ]
